hash-format = "sha256"

[[files]]
file = "mods/chunky.pw.toml"
hash = "140cdf4490191191625b37ddf04470a88c882cc111ec00db23ae38b04d1ddfe2"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "8d388f7e7a22409b26a6686c01c1c13a2acefda461f64f95f78969b340cdfd50"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "d88ba499ff5646a392d30c5c90dac8465a0d16a7bc97cb30d74bce17903dba90"
metafile = true

[[files]]
file = "mods/floodgate.pw.toml"
hash = "7380955b88299f1c4f894a47c32fa6b8c9f25548dd4e17d384e4bba7b5dd9488"
metafile = true

[[files]]
file = "mods/geyser.pw.toml"
hash = "26f1136d851da18ad1c5dea577706c3655fa90b69a99c51a141728e7fc1a7691"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2ee74f2b7618163678b45f3acae5bace4c97afd1d8e4947b35645dc52e22b261"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "108aaf5e8735bcae2dde313d73dcbcec226ec2e49af2efaccb25b9ff6caa2c41"
metafile = true
