name = "SanMartianGamingServer"
author = "bohemianjack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9715b631bf20a22f4ee20eba1ea145207b81690d66de4e5b0190cade17e6d54f"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21,1.21.2,1.21.3,1.21.4", "1.21.x,1.21.1,1.21.4"]
