name = "San Martian Minecraft Server"
author = "jakechristian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7054453ffadf0bfca23cffc1a37e764c43c0f62b337b6e34aaa2a8b92a926f6f"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
