name = "SanMartianGamingServer"
author = "bohemianjack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dd5e0b923c11286809800f11e3b4af3b815e5f2df2a260e3300512b83194cd1"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
